/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedKarteikartenRouteImport } from './routes/_authenticated/karteikarten'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExamIndexRouteImport } from './routes/_authenticated/exam.index'
import { Route as AuthenticatedExamRunRouteImport } from './routes/_authenticated/exam.run'
import { Route as AuthenticatedExamSessionIdResultRouteImport } from './routes/_authenticated/exam.$sessionId.result'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKarteikartenRoute =
  AuthenticatedKarteikartenRouteImport.update({
    id: '/karteikarten',
    path: '/karteikarten',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamIndexRoute = AuthenticatedExamIndexRouteImport.update({
  id: '/exam/',
  path: '/exam/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamRunRoute = AuthenticatedExamRunRouteImport.update({
  id: '/exam/run',
  path: '/exam/run',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamSessionIdResultRoute =
  AuthenticatedExamSessionIdResultRouteImport.update({
    id: '/exam/$sessionId/result',
    path: '/exam/$sessionId/result',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/karteikarten': typeof AuthenticatedKarteikartenRoute
  '/exam/run': typeof AuthenticatedExamRunRoute
  '/exam/': typeof AuthenticatedExamIndexRoute
  '/exam/$sessionId/result': typeof AuthenticatedExamSessionIdResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/karteikarten': typeof AuthenticatedKarteikartenRoute
  '/exam/run': typeof AuthenticatedExamRunRoute
  '/exam': typeof AuthenticatedExamIndexRoute
  '/exam/$sessionId/result': typeof AuthenticatedExamSessionIdResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/karteikarten': typeof AuthenticatedKarteikartenRoute
  '/_authenticated/exam/run': typeof AuthenticatedExamRunRoute
  '/_authenticated/exam/': typeof AuthenticatedExamIndexRoute
  '/_authenticated/exam/$sessionId/result': typeof AuthenticatedExamSessionIdResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/karteikarten'
    | '/exam/run'
    | '/exam/'
    | '/exam/$sessionId/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/karteikarten'
    | '/exam/run'
    | '/exam'
    | '/exam/$sessionId/result'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/karteikarten'
    | '/_authenticated/exam/run'
    | '/_authenticated/exam/'
    | '/_authenticated/exam/$sessionId/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/karteikarten': {
      id: '/_authenticated/karteikarten'
      path: '/karteikarten'
      fullPath: '/karteikarten'
      preLoaderRoute: typeof AuthenticatedKarteikartenRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exam/': {
      id: '/_authenticated/exam/'
      path: '/exam'
      fullPath: '/exam/'
      preLoaderRoute: typeof AuthenticatedExamIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exam/run': {
      id: '/_authenticated/exam/run'
      path: '/exam/run'
      fullPath: '/exam/run'
      preLoaderRoute: typeof AuthenticatedExamRunRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exam/$sessionId/result': {
      id: '/_authenticated/exam/$sessionId/result'
      path: '/exam/$sessionId/result'
      fullPath: '/exam/$sessionId/result'
      preLoaderRoute: typeof AuthenticatedExamSessionIdResultRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKarteikartenRoute: typeof AuthenticatedKarteikartenRoute
  AuthenticatedExamRunRoute: typeof AuthenticatedExamRunRoute
  AuthenticatedExamIndexRoute: typeof AuthenticatedExamIndexRoute
  AuthenticatedExamSessionIdResultRoute: typeof AuthenticatedExamSessionIdResultRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKarteikartenRoute: AuthenticatedKarteikartenRoute,
  AuthenticatedExamRunRoute: AuthenticatedExamRunRoute,
  AuthenticatedExamIndexRoute: AuthenticatedExamIndexRoute,
  AuthenticatedExamSessionIdResultRoute: AuthenticatedExamSessionIdResultRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
